### ISSUE TITLE
ch03 - 3  Create an object that will hold methods for adding, multiplying, and factorial operations

### ISSUE THREAD

**Issue by ghost** [antoniopacheco/tekmexJS#1]
The factorial function is usually implemented recursively for demonstration purposes because it is very easy to implement that way. It is, however, a very bad idea to implement it recursively for any serious, production, purposes. Avoid doing it unless explicitly asked to do so.

**Comment by antoniopacheco** [comment]
Changed for a loop in commit 
https://github.com/antoniopacheco/tekmexJS/commit/7e08e4e9953df2cd33647881fc1cf343eb0309a3
