### ISSUE TITLE
Ch03 - 4 Custom object with mock image data

### ISSUE THREAD

**Issue by ghost** [antoniopacheco/tekmexJS#2]
This exercise does not involve the use of canvas in any way. You are to follow the example code and create an object that will hold its data in an array. You are then to create a function to be able to access the data as if it were a 2-dimensional array. Make sure that the size of the array corresponds to the dimensions specified for the image.

**Comment by antoniopacheco** [comment]
Canvas removed and store it as a dummy data
https://github.com/antoniopacheco/tekmexJS/commit/73165d3e686005bd97679bc04dc66b3086d8e75c

**Comment by ghost** [comment]
The problem is not fixed. Please don't close until they have been verified.

**Comment by antoniopacheco** [comment]
If is only a validation issue it is fix 
https://github.com/antoniopacheco/tekmexJS/commit/d48fb657a22318a04e2bce43e47a9e5adab49f4c

**Comment by antoniopacheco** [comment]
Changed multidimensional array to a single array
https://github.com/antoniopacheco/tekmexJS/commit/c1e7be27f299b93dcde846a5143cebe5572ade34

**Comment by antoniopacheco** [comment]
Removed color property
https://github.com/antoniopacheco/tekmexJS/commit/f0769764497a0868743d26e7d8f888a8350ea651
