### ISSUE TITLE
Ch03 - 5 Create a function that will print out the properties of an object

### ISSUE THREAD

**Issue by ghost** [antoniopacheco/tekmexJS#3]
You need to rethink your approach for printing out the properties belonging to the instance. It would not work for the following example:

``` javascript
var obj = {a: 1, b:2};
Object.prototype.c = 3;

printObjProp(obj, true);
```

**Comment by antoniopacheco** [comment]
another approach using getOwnPropertyNames
https://github.com/antoniopacheco/tekmexJS/commit/f83513a22af8d177eba6108ae73d2d345092c1ac
