### ISSUE TITLE
Ch04 - 4 Write a function that will accept any number of arguments and print out their data type

### ISSUE THREAD

**Issue by ghost** [antoniopacheco/tekmexJS#5]
- Getting incorrect output for the following cases:
  - new String(" ")
  - new Number(42)

``` javascript
dataType (new String("helo world"), new Number(42)); 
```

**Comment by antoniopacheco** [comment]
returning the constructor name, instead of a string
https://github.com/antoniopacheco/tekmexJS/commit/34384f4063fd934d8d060ff175ffa43b3540ceb1
