### ISSUE TITLE
Ch04 - 6 Function to calculate distance from arrays or parameter list

### ISSUE THREAD

**Issue by ghost** [antoniopacheco/tekmexJS#6]
- It would be best to not repeat yourself. If you've already written the code for distance of 2D and 3D points, make use of it instead of rewriting it for arrays.

**Comment by antoniopacheco** [comment]
Great Idea!
https://github.com/antoniopacheco/tekmexJS/commit/3fec472d7aa66bd0bdff1c16ae4f29168354d96e
